name: Build & Deploy Docker to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read        # for actions/checkout
  id-token: write       # for azure/login OIDC

env:
  WEBAPP_NAME: pup-cloud2           # Azure Web App (lower-case)
  ACR_NAME:    pupcloud2            # ACR short name (no .azurecr.io)
  IMAGE_REPO:  pup-cloud2           # repo name inside ACR
  TAG_NAME:    alroca               # exact GitHub Release tag
  ASSET_FILE:  pokedex_resnet50.h5


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the code
      - name: 📂 Checkout repo
        uses: actions/checkout@v4

      # 2) Azure login (OIDC)
      - name: 🔑 Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3) ACR login
      - name: 🐳 ACR login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io

      # 4) Build & push Docker image
      - name: 🏗️ Build & push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          FULL_IMAGE=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_REPO }}:$IMAGE_TAG

          MODEL_URL="https://github.com/${{ github.repository }}/releases/download/${{ env.TAG_NAME }}/${{ env.ASSET_FILE }}"

          docker build \
            --build-arg MODEL_URL="$MODEL_URL" \
            --build-arg ASSET_FILE="${{ env.ASSET_FILE }}" \
            -t "$FULL_IMAGE" .
          docker push "$FULL_IMAGE"



      # 5) Deploy the freshly‑pushed image
      - name: 🚀 Deploy to Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name:             ${{ env.WEBAPP_NAME }}
          resource-group-name:  Pup-Cloud2_group     # ← corrected
          images:               ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_REPO }}:${{ github.sha }}
