name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your source repo (the one with Dockerfile, predict_server.py, etc.)
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configure git user for commits
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      # 3. Clone the Hugging Face Space repository into a subdir
      - name: Clone HF Space repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://AlbertoRoca96-web:${HF_TOKEN}@huggingface.co/spaces/AlbertoRoca96-web/pointkedex hf-space
          ls -R hf-space | head -100

      # 4. Copy needed files into the Space repo (overwrite)
      - name: Sync files
        run: |
          # adjust these paths if your project structure differs
          rsync -a --delete \
            Dockerfile \
            predict_server.py \
            index.html app.js config.js flavor_text.json class_indices.json \
            README.md \
            hf-space/
          # ensure README has Docker front-matter
          if ! head -n3 hf-space/README.md | grep -q 'sdk: docker'; then
            cat <<'EOF' > hf-space/README.md
---
sdk: docker
app_port: 7860
---
EOF
          fi

      # 5. Commit & push if there are changes
      - name: Commit & push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf-space
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to push."
          else
            git commit -m "Sync app files from GitHub main"
            git push
          fi
