name: Deploy to HF Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Login to HF Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install --quiet --user huggingface_hub
          huggingface-cli login --token "$HF_TOKEN"    # no --yes required

      - name: Push to Space (with embedded PAT)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: AlbertoRoca96-web
        run: |
          git push --force https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/pointkedex \
            main:main
