name: Deploy to HF Space

on:
  push:
    branches: [main]          # run on every push to main
  workflow_dispatch:          # manual “Run workflow” button

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the code – sub-modules off (avoids earlier 128 error)
      - uses: actions/checkout@v4
        with: { submodules: 'false' }

      # 2️⃣ Enable Git LFS inside the runner (needed for your .h5 file)
      - name: Enable Git LFS
        run: git lfs install --local

      # 3️⃣ Log in to Hugging Face Hub (non-interactive CLI)
      - name: Login to HF Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}   # PAT with *write* scope
        run: |
          pip install --quiet --user huggingface_hub
          huggingface-cli login --token "$HF_TOKEN" --add-to-git-credential

      # 4️⃣ Push the current commit to the *new* Space repo
      - name: Push to Space
        run: |
          git remote add space https://huggingface.co/spaces/AlbertoRoca96-web/pointkedex
          # push the exact commit SHA so parallel builds don't race
          git push --force space ${{ github.sha }}:main
