# .github/workflows/deploy.yml
name: Deploy to HF Space
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name  "github-actions"
      - name: Login to HF
        env: { HF_TOKEN: ${{ secrets.HF_TOKEN }} }
        run: |
          pip install --quiet --user huggingface_hub
          huggingface-cli login --token "$HF_TOKEN" --yes
      - name: Push to Space
        run: |
          git remote add space https://huggingface.co/spaces/AlbertoRoca96-web/pointkedex-api
          git push --force space ${{ github.sha }}:main
