# .github/workflows/main_pup-cloud.yml
# Build & deploy everything in repo root to Azure Functions (Linux Consumption).

name: Build and deploy Python project to Azure Function App – Pup‑Cloud

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'
  PACKAGE_ZIP:    release.zip       # the file we deploy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install requirements
      run: pip install -r requirements.txt

    # ── Create the deployment package from *repo root* ──
    - name: Create ZIP package
      run: |
        zip -r "${{ env.PACKAGE_ZIP }}" . \
            -x "venv/*" ".git/*" ".github/*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: ${{ env.PACKAGE_ZIP }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write          # OIDC
      contents: read

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: Azure login (OIDC)
      uses: azure/login@v2
      with:
        client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB70A3F269874835BA3BDC2E8DD09B91 }}
        tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_0BCEA4CB4732493CBEEBDDCF82D43069 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8CEBB76FBDB54BA3AE0AC59A264FA309 }}

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name:  Pup-Cloud
        slot-name: Production
        package:   ${{ env.PACKAGE_ZIP }}
