# .github/workflows/main_pup-cloud2.yml
name: Build & Deploy Docker to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read        # for actions/checkout
  id-token: write       # for azure/login OIDC

env:
  WEBAPP_NAME: Pup-Cloud2
  ACR_NAME:    pupcloud2
  IMAGE_TAG:   ${{ github.sha }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build & Push image to ACR
        run: |
          IMAGE_FULL=${{ env.ACR_NAME }}.azurecr.io/${{ env.WEBAPP_NAME }}:${{ env.IMAGE_TAG }}
          echo "Building $IMAGE_FULL"
          docker build -t $IMAGE_FULL .
          docker push $IMAGE_FULL

      - name: Deploy to Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          images:   ${{ env.ACR_NAME }}.azurecr.io/${{ env.WEBAPP_NAME }}:${{ env.IMAGE_TAG }}
