# .github/workflows/deploy_container.yml
name: Build & Deploy Docker to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read        # for checkout
  id-token: write       # for OIDC

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # these env vars are available to all steps in this job
    env:
      WEBAPP_NAME: Pup-Cloud2
      ACR_NAME:    pupcloud2            # your registry short name
      IMAGE_TAG:   ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Register AlertsManagement provider
        run: |
          az provider register --namespace Microsoft.AlertsManagement

      - name: ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build & Push image to ACR
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.WEBAPP_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.WEBAPP_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          images:   ${{ env.ACR_NAME }}.azurecr.io/${{ env.WEBAPP_NAME }}:${{ env.IMAGE_TAG }}
