name: Deploy to HF Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to HF Hub
        uses: huggingface/huggingface-cli-login@v1
        with:
          huggingface_token: ${{ secrets.HF_TOKEN }}

      - name: Push to Space
        run: |
          git remote add space https://huggingface.co/spaces/AlbertoRoca96-web/pointkedex-api
          git push --force space ${{ github.sha }}:main
