name: Build & Deploy Docker to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read      # for actions/checkout
  id-token: write     # only needed if you switch back to OIDC

env:
  WEBAPP_NAME: Pup-Cloud2
  ACR_NAME:    pupcloud2  # ← your registry “short name” (no “.azurecr.io”)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 🔑 Login to Azure (Service Principal)
        uses: azure/login@v1
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret:   ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: 🐳 Login to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: 🏗️ Build & push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}   # shorten if you like
          FULL_IMAGE=${{ env.ACR_NAME }}.azurecr.io/${{ env.WEBAPP_NAME }}:$IMAGE_TAG

          docker build -t $FULL_IMAGE .
          docker push    $FULL_IMAGE

      - name: 🚀 Deploy to Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          images:   ${{ env.ACR_NAME }}.azurecr.io/${{ env.WEBAPP_NAME }}:${GITHUB_SHA::8}
