# .github/workflows/main_pup-cloud.yml
# Deploy the repo‑root (Python Function + static assets) to Azure Functions
# Linux Consumption plan – no manual zip/unzip steps.

name: Deploy Python Function App – Pup‑Cloud

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read          # checkout
  id-token: write         # federated (OIDC) login to Azure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ pull the latest commit
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2 ▸ sign in to Azure (RBAC service‑principal creds are stored as GitHub Secrets)
    - name: Azure login (OIDC)
      uses: azure/login@v2
      with:
        client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB70A3F269874835BA3BDC2E8DD09B91 }}
        tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_0BCEA4CB4732493CBEEBDDCF82D43069 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8CEBB76FBDB54BA3AE0AC59A264FA309 }}

    # 3 ▸ push everything in repo‑root to the Function App.
    #     The action zips the contents on‑the‑fly and sets WEBSITE_RUN_FROM_PACKAGE.
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name:  Pup-Cloud          # ← exact Function App name
        slot-name: Production
        package:   '.'                # deploy *this* folder (repo root)
