# Docs for the Azure Web Apps Deploy action:
#   https://github.com/azure/functions-action
# More GitHub Actions for Azure:
#   https://github.com/Azure/actions
# More info: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - Pup-Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # the ZIP we create in the build job
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './release.zip'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: test step could go here

      # Zip the CONTENTS of backend/ (not the folder itself)
      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB70A3F269874835BA3BDC2E8DD09B91 }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_0BCEA4CB4732493CBEEBDDCF82D43069 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8CEBB76FBDB54BA3AE0AC59A264FA309 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name:  'Pup-Cloud'
          slot-name: 'Production'
          package:   ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
